[project]
name = "qic_ssh"
version = "0.1.0"
dependencies = [
    "numpy",
    "scipy",
    "physics-tenpy"
]
description = "Implementation of SSH for QIC exam"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.4"]